# Generated by Django 4.1.3 on 2022-12-18 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Moneda', '0002_usuario_delete_jugador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='balance',
            field=models.IntegerField(default=10000),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
