# Generated by Django 4.1.3 on 2022-12-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Moneda', '0003_alter_usuario_balance_alter_usuario_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('mail', models.EmailField(max_length=254)),
                ('cel', models.IntegerField()),
                ('mensaje', models.CharField(max_length=150)),
            ],
        ),
    ]
