# Generated by Django 4.1.3 on 2022-12-18 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Moneda', '0004_contacto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='mensaje',
            new_name='msj',
        ),
    ]
