# Generated by Django 4.1.3 on 2022-12-18 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Moneda', '0005_rename_mensaje_contacto_msj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
    ]
